version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4.13-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
        mongo-data:
